repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.4
  hooks:
    - id: ruff
      name: Ruff lint check
      args: ["--config=pyproject.toml"]
    - id: ruff-format
      name: Ruff formatter
      args: ["--config=pyproject.toml"]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
    - id: mypy
      name: Static type checker (mypy)
      additional_dependencies:
        - types-requests
      args: ["--config-file=pyproject.toml"]
